### ISSUE TITLE
impossible to use ShareStream with purescript-node-process

### ISSUE THREAD

**Issue by srghma** [purescript-node/purescript-node-child-process#23] opened 2020-10-07 17:32 UTC
https://github.com/purescript-node/purescript-node-child-process/blob/887b252ef85975f4cf31dfd9079f6d98d905fc1b/src/Node/ChildProcess.purs#L482

when I try to write custom something like

```
import Node.Process as Node.Process


noInputOnlyOutput = [Just Ignore, Just (ShareStream Node.Process.stdout), Just Pipe]
```

I cannot 

https://github.com/purescript-node/purescript-node-process/blob/88871d84a69f47dd2d1d9eccd7cc942be4457d46/src/Node/Process.purs#L125-L126

```
[1/1 TypesDoNotUnify] webpack/NextjsWebpack/Utils/OnFilesChangedRunCommand.purs:26:53

  26  noInputOnlyOutput = [Just Ignore, Just (ShareStream Node.Process.stdout), Just Pipe]
                                                          ^^^^^^^^^^^^^^^^^^^

  Could not match type

    ( write :: Write
    )

  with type

    r0
```

____________

it also cannot be rewritten with Exists 

```
data StdIOBehaviour
  = Pipe
  | Ignore
  | ShareStream (Exists Stream)
  | ShareFD FS.FileDescriptor
```

```
  Could not match kind

    # Type

  with kind

    Type
```

**Comment by srghma** [comment] 2020-10-07 17:36
seems like we have to wait for PolyKinds and then rewrite it with Exists, and for now use unsafeCoerce like

```
import Node.Stream (Stream, Write)
import Unsafe.Coerce (unsafeCoerce)

forget :: forall r . Stream ( write :: Write ) -> Stream r
forget = unsafeCoerce

noInputOnlyOutput = [Just Ignore, Just (ShareStream (forget Node.Process.stdout)), Just (ShareStream (forget Node.Process.stderr))]
```

**Comment by hdgarrood** [comment] 2020-10-10 03:47
Thanks for the report. This is a duplicate of #8.

**Closed by hdgarrood** 2020-10-10 03:47 UTC
